version: '3'
services:
  api:
    build: api/.
    ports: 
      - 4000:5000
    depends_on:
      - mysql

  mysql:
    build: mysql/.
      args:
        - MYSQL_USER=rm340189
        - MYSQL_PASSWORD=leonardo   
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
      - /docker-entrypoint-initdb.d/spotify_ddl.sql
    environment:
      MYSQL_USER: rm340189
      MYSQL_PASSWORD: leonardo
      MYSQL_ROOT_PASSWORD: fiap
      MYSQL_DATABASE: 53bdt_db 
