version: '3'
services:
  api:
    build: api/.
    ports: 
      - 4000:5000
    depends_on:
      - mysql

  mysql:
    build: mysql/.
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: rm340189
      MYSQL_ROOT_PASSWORD: leonardo
      MYSQL_DATABASE: 53bdt_db